[package]
name = "sc-visualizer"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
controller-mapper = { path = "../../crates/controller-mapper" }
bridge-output = { path = "../../crates/bridge-output" }
eframe.workspace = true
gamepad-state = { path = "../../crates/gamepad-state" }
recording = { path = "../../crates/recording" }
serde_json.workspace = true
steam-controller-device = { path = "../../crates/steam-controller-device" }
steam-controller-protocol = { path = "../../crates/steam-controller-protocol" }

[lints]
workspace = true
