[package]
name = "release-updater"
version = "1.9.0"
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
app-paths = { path = "../app-paths" }
base64.workspace = true
bridge-output = { path = "../bridge-output" }
clap.workspace = true
ed25519-dalek.workspace = true
semver.workspace = true
rustix.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
serialport.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio.workspace = true

[lints]
workspace = true
