[package]
name = "bridge-core"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
bridge-output = { path = "../bridge-output" }
controller-mapper = { path = "../controller-mapper" }
gamepad-state = { path = "../gamepad-state" }
steam-controller-protocol = { path = "../steam-controller-protocol" }

[lints]
workspace = true
