[package]
name = "sc-bridge"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
bridge-core = { path = "../../crates/bridge-core" }
bridge-output = { path = "../../crates/bridge-output" }
bridge-runtime = { path = "../../crates/bridge-runtime" }
ctrlc.workspace = true
recording = { path = "../../crates/recording" }

[lints]
workspace = true
