[package]
name = "steam-controller-device"
version = "1.10.0"
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
app-paths = { path = "../../host/app-paths" }
fs4.workspace = true
steam-controller-protocol = { path = "../steam-controller-protocol" }

[target.'cfg(target_os = "macos")'.dependencies]
hidapi = { workspace = true, features = ["macos-shared-device"] }

[target.'cfg(target_os = "linux")'.dependencies]
hidapi = { workspace = true, features = ["linux-native"] }

[lints]
workspace = true
