[package]
name = "desktop-input"
version = "1.10.0"
edition.workspace = true
license.workspace = true
publish = false
repository.workspace = true

[dependencies]
desktop-bindings = { path = "../desktop-bindings" }

[target.'cfg(target_os = "macos")'.dependencies]
enigo.workspace = true
objc2-core-graphics.workspace = true
objc2-io-kit.workspace = true

[lints]
workspace = true
